### ISSUE TITLE
etcd fails to start without the log_dir

### ISSUE THREAD

**Issue by hackzilla** [solarkennedy/puppet-etcd#6]
Problem:

```
/usr/bin/etcd -config /etc/etcd/etcd.conf >> /var/log/etcd/etcd.out
bash: /var/log/etcd/etcd.out: No such file or directory
```

Fix:

```
mkdir /var/log/etcd
```

**Comment by fatmcgav** [comment]
@hackzilla Am I right in thinking you're running on Debian/Ubuntu? 

As on EL that log dir is created by the etcd RPM... 
Though I guess we could handle creation aswell...

**Comment by hackzilla** [comment]
Ubuntu 14.04

**Comment by hackzilla** [comment]
couldn't hurt to ensure it was created

**Comment by fatmcgav** [comment]
Agreed, will see what I can work up :)

**Comment by fatmcgav** [comment]
@hackzilla I've just pushed a351d9427d5a93df0308ca20cb59d4019d841fbc to my [develop](https://github.com/fatmcgav/puppet-etcd/tree/develop) repo. Can you test and confirm?

**Comment by hackzilla** [comment]
I must be doing something wrong, as I can't get librarian to install it.

```
mod "KyleAnderson/etcd",
  :git => "https://github.com/fatmcgav/puppet-etcd.git",
  :ref => 'develop'
```

```
root@puppet-master:/etc/puppet# librarian-puppet update KyleAnderson/etcd
Unable to find module KyleAnderson/etcd

root@puppet-master:/etc/puppet# librarian-puppet install --clean=true
Cannot bounce Puppetfile.lock!
```

**Comment by fatmcgav** [comment]
I've got a feeling this might be a Librarian-puppet issue, rather than specifically a module issue... 

I have fixed a dependency mis-match between the Modulefile and Puppetfile, but in my testing I'm still getting failures:

> $ librarian-puppet install
> /home/gavinw/librarian-test/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/puppetlabs-stdlib/4.2.2/puppetlabs-stdlib does not exist, something went wrong. Try removing it manually

Can you confirm what version of librarian-puppet you're using?

**Comment by hackzilla** [comment]
```
librarian-puppet version
librarian-puppet v1.0.2
```

**Comment by hackzilla** [comment]
After updating librarian-puppet to v1.1.2, I have made some progress, but I might be running into #8 issue now.

When I have this in my Puppetfile:

```
mod "KyleAnderson/etcd",
  :git => "https://github.com/fatmcgav/puppet-etcd.git",
  :ref => 'develop'
```

```
librarian-puppet install 
Replacing Puppet Forge API URL to use v3 https://forgeapi.puppetlabs.com. You should update your Puppetfile
Replacing Puppet Forge API URL to use v3 https://forgeapi.puppetlabs.com. You should update your Puppetfile
/etc/puppet/.tmp/librarian/cache/source/puppet/forge/forgeapi_puppetlabs_com/puppetlabs-stdlib/4.2.2/puppetlabs-stdlib does not exist, something went wrong. Try removing it manually
```

If I change back to `mod "KyleAnderson/etcd"` then install proceeds normally.

**Comment by solarkennedy** [comment]
I can't get librarian-puppet to work either. r10k works for me?

**Comment by fatmcgav** [comment]
It's been accepted as an issue on librarian-puppet - rodjek/librarian-puppet#234 - so hopefully should have a fix soon :)

**Comment by hackzilla** [comment]
Librarian-puppet has been updated.

```
librarian-puppet version
librarian-puppet v1.3.1
```

```
root@puppet-master:/etc/puppet# librarian-puppet install --clean=true
Replacing Puppet Forge API URL to use v3 https://forgeapi.puppetlabs.com. You should update your Puppetfile
```

So it looks like I proceed with the test.

**Comment by hackzilla** [comment]
works for me :+1:

**Comment by fatmcgav** [comment]
Cheers for confirming.
