### ISSUE TITLE
Fix tests :( 

### ISSUE THREAD

**Issue by fatmcgav** [solarkennedy/puppet-etcd#8]
It looks like 46e53ce5df3fbfb87dea7c8eabf46241b11acb08 broke Librarian-puppet. 

Will try and get it fixed this evening...

**Comment by hackzilla** [comment]
Librarian-puppet has been updated.

**Comment by solarkennedy** [comment]
Close-able? Right?
https://travis-ci.org/solarkennedy/puppet-etcd/builds

**Comment by fatmcgav** [comment]
Yep, looks like it's all fixed...
