### ISSUE TITLE
Running etcd as user etcd - nil response

### ISSUE THREAD

**Issue by hackzilla** [solarkennedy/puppet-etcd#9]
starting etcd

```
[etcd] Aug 26 10:36:46.621 INFO      | stats-web1.ukwm.local starting in peer mode
[etcd] Aug 26 10:36:46.730 WARNING   | [ae] Error: nil response
[etcd] Aug 26 10:36:46.826 WARNING   | [ae] Error: nil response
[etcd] Aug 26 10:36:46.928 WARNING   | [ae] Error: nil response
[etcd] Aug 26 10:36:47.026 WARNING   | [ae] Error: nil response
[etcd] Aug 26 10:36:47.127 WARNING   | [ae] Error: nil response
```

I'm not 100% sure what is going on here.
If I run the command as root, it works perfectly.

I thought it was pam, but now I'm not so sure.

**Comment by hackzilla** [comment]
```
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04 LTS"
```

```
etcdctl --version
etcdctl version 0.4.4
```

**Comment by hackzilla** [comment]
Looks like I had the wrong ownership of the etcd folders.

```
ls -lath /var/lib/etcd/
total 72K
-rw-------  1 root root  54K Aug 26 10:31 log
drwx------  2 root root 4.0K Aug 26 10:30 snapshot
drwxr-x---  3 etcd etcd 4.0K Aug 26 10:30 .
-rw-------  1 root root  177 Aug 26 10:30 conf
drwxr-xr-x 43 root root 4.0K Aug 13 11:13 ..
```

**Comment by fatmcgav** [comment]
@hackzilla How did you install etcd? Package or source? 

If packaged, would expect the directory permissions to be setup correctly... Though that does raise the question of what happens with permissions if you want to run as a non-standard user...

**Comment by hackzilla** [comment]
It's built from source as it allows me to match coreos releases.

```
  file { '/root/etcd.deb':
    source           => 'puppet:///files/etcd.deb',
    before           => Class['etcd'],
  }

  exec { '/usr/bin/dpkg -i /root/etcd.deb':
    require          => File['/root/etcd.deb'],
  }

  class { 'etcd':
    discovery               => true,
    discovery_token         => '<token>',
    peer_election_timeout   => 500,
    peer_heartbeat_interval => 100,
    addr                    => "${::ipaddress_eth0}:4001",
    bind_addr               => "",
    peer_addr               => "${::ipaddress_eth0}:7001",
    peer_bind_addr          => "",
    snapshot                => true,
    verbose                 => false,
    very_verbose            => false,
  }
```

**Comment by fatmcgav** [comment]
Built from source but looks like you've packaged it into a Deb? 

Do Deb package allow you to set file ownership upon installation? As I suspect that your deb will set the files to `root:root` ownership...

**Comment by hackzilla** [comment]
I'm using https://github.com/solarkennedy/etcd-packages to make the package, which upon closer examination, I can see specifies `--deb-user root --deb-group root`

**Comment by fatmcgav** [comment]
That would do it... :) 

Could you try a rebuild specifying 'etcd' as user and group, and report back? 

If that is the case, I can't think of a sensible method to fix in code, other than possibly a hacky `chown` exec...

**Comment by hackzilla** [comment]
I did delete the directory and reapplied puppet, and it was perfectly recreated.

**Comment by fatmcgav** [comment]
Cool, ok... Are you happy for me to close this bug then as an external issue?

**Comment by hackzilla** [comment]
removed etcd, and /var/lib/etcd

then reinstalled, no directory.

I guess that user/group is only for binary ownership.

Looks like directory is only created on first launch, which is probably as it should be.

**Comment by fatmcgav** [comment]
Ah, yeh... Switching the user the process runs at between `etcd` and `root` probably would cause issues... 

Glad we got u working though :)

**Comment by hackzilla** [comment]
thanks :+1: 

Hopefully I can actually get round to deploying my app.  Just keep running into etcd issues.

**Comment by fatmcgav** [comment]
It's always fun with new tools and tech's... ;)
